"""Generate the orbit figure markup (feedback 16: all the icons from Harsh's image).

Positions are computed, not typed: each item sits mid-band at an angle
measured clockwise from the top. Angles were chosen so that every icon and
its name fits inside its band at 560px+ (labels on), and so that each ring
is symmetric under its curved name.
"""
import math, pathlib

R_IN, R_MID, R_OUT = 19.0, 33.5, 50.0          # percent of the square stage
MID_R = (R_IN + R_MID) / 2                      # 26.25
OUT_R = (R_MID + R_OUT) / 2                     # 41.75

ICONS = {
    'speaking': '<path d="M4 5.6A2.6 2.6 0 0 1 6.6 3h10.8A2.6 2.6 0 0 1 20 5.6v7.8a2.6 2.6 0 0 1-2.6 2.6H11l-4.4 4v-4A2.6 2.6 0 0 1 4 13.4z"/><path d="M8 8.4h8M8 11.4h5"/>',
    'podcasts': '<rect x="9.5" y="2.5" width="5" height="10" rx="2.5"/><path d="M12 12.5v8M9 20.5h6"/><path d="M16.2 3.3a6 6 0 0 1 0 8.4M7.8 3.3a6 6 0 0 0 0 8.4M18.4 1.2a9 9 0 0 1 0 12.6M5.6 1.2a9 9 0 0 0 0 12.6"/>',
    'panels': '<rect x="2.5" y="5" width="19" height="14" rx="2"/><path d="M8.8 5v14M15.2 5v14"/><circle cx="5.65" cy="10.4" r="1.4"/><circle cx="12" cy="10.4" r="1.4"/><circle cx="18.35" cy="10.4" r="1.4"/><path d="M4.1 15.6c.4-1.2.9-1.8 1.55-1.8s1.15.6 1.55 1.8M10.45 15.6c.4-1.2.9-1.8 1.55-1.8s1.15.6 1.55 1.8M16.8 15.6c.4-1.2.9-1.8 1.55-1.8s1.15.6 1.55 1.8"/>',
    'publications': '<path d="M6.2 2.5h8.3L19 7v13.2a1.3 1.3 0 0 1-1.3 1.3H6.2a1.3 1.3 0 0 1-1.3-1.3V3.8a1.3 1.3 0 0 1 1.3-1.3z"/><path d="M14.3 2.6V7.2H19"/><path d="M8.4 11.6h7.2M8.4 14.9h7.2M8.4 8.3h3.4"/>',
    'media': '<rect x="2.5" y="6.5" width="13" height="11" rx="2.2"/><path d="M15.5 10.4 21.5 7v10l-6-3.4z"/>',
    'partnerships': '<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>',
    'clients': '<circle cx="11" cy="7.4" r="3.6"/><path d="M4 21v-1.6A4.2 4.2 0 0 1 8.2 15.2h5.6a4.2 4.2 0 0 1 4.2 4.2V21"/><circle class="orbit__dot" cx="19.4" cy="4.6" r="2.2"/>',
    'hosts': '<rect x="9" y="2.5" width="6" height="11" rx="3"/><path d="M5.8 10.8a6.2 6.2 0 0 0 12.4 0M12 17v4.2M8.8 21.2h6.4"/>',
    'partners': '<path d="m11 17 2 2a1 1 0 1 0 3-3"/><path d="m14 14 2.5 2.5a1 1 0 1 0 3-3l-3.88-3.88a3 3 0 0 0-4.24 0l-.88.88a1 1 0 1 1-3-3l2.81-2.81a5.79 5.79 0 0 1 7.06-.87l.47.28a2 2 0 0 0 1.42.25L21 4"/><path d="m21 3 1 11h-2"/><path d="M3 3 2 14l6.5 6.5a1 1 0 1 0 3-3"/><path d="M3 4h8"/>',
    'audiences': '<circle cx="4.8" cy="9" r="2.3"/><path d="M6.4 14.4H5.2A3.4 3.4 0 0 0 1.8 17.8V20"/><circle cx="19.2" cy="9" r="2.3"/><path d="M17.6 14.4h1.2a3.4 3.4 0 0 1 3.4 3.4V20"/><circle cx="12" cy="7.2" r="3"/><path d="M6.8 20.5v-1.3a4.2 4.2 0 0 1 4.2-4.2h2a4.2 4.2 0 0 1 4.2 4.2v1.3"/>',
    'opportunities': '<path d="M3 21h18"/><path d="M6.5 17.5V14M11 17.5v-5M15.5 17.5v-3M20 17.5V9"/><path d="m4.5 11 4.5-4 3.5 2.6L19 3.6"/><path d="M15.6 3.4H19v3.4"/>',
}

MID = [  # name, icon, angle
    ('Speaking', 'speaking', 308.6),
    ('Podcasts', 'podcasts', 51.4),
    ('Panels', 'panels', 264.6),
    ('Publications', 'publications', 95.4),
    ('Media', 'media', 200.0),
    ('Partnerships', 'partnerships', 160.0),
]
OUT = [
    ('Clients who<br>need you', 'clients', 270.0),
    ('Hosts seeking<br>experts', 'hosts', 90.0),
    ('Strategic<br>partners', 'partners', 130.0),
    ('New<br>audiences', 'audiences', 230.0),
    ('Opportunities', 'opportunities', 180.0),
]


def pos(r, a):
    t = math.radians(a)
    return round(50 + r * math.sin(t), 2), round(50 - r * math.cos(t), 2)


def item(name, icon, a, r):
    x, y = pos(r, a)
    return (f'            <li class="orbit__item" style="--x:{x}%;--y:{y}%"><span class="orbit__ico">'
            f'<svg viewBox="0 0 24 24">{ICONS[icon]}</svg></span><span class="orbit__t">{name}</span></li>')


def arc(rad):
    a = math.radians(80)
    x1, y = 500 - rad * math.sin(a), 500 - rad * math.cos(a)
    return f"M{x1:.1f} {y:.1f}A{rad} {rad} 0 0 1 {1000 - x1:.1f} {y:.1f}"


mid_items = "\n".join(item(n, i, a, MID_R) for n, i, a in MID)
out_items = "\n".join(item(n, i, a, OUT_R) for n, i, a in OUT)

html = f'''    <!-- Feedback 13-16 (28 Sep): Harsh's concentric diagram, from the centre
         out: you are here (the paragraph's own first lines), you need
         distribution, known beyond your circle. Feedback 16: all the icons
         from his image are back. Item positions are generated by
         _art/gen_orbit.py (exact angles, mid-band) so each icon and its name
         fits inside its ring; on phones the rings carry the icons and the
         names are kept for screen readers. Section 64 of oyss.css. -->
    <figure class="orbit" data-lit data-cue="2">
      <p class="orbit__sr">You are here: client results, a reputation, referrals and a full calendar, inside your own
        network. Around you, you need distribution: speaking, podcasts, panels, publications, media and partnerships.
        Around that, known beyond your circle: clients who need you, hosts seeking experts, strategic partners, new
        audiences and opportunities.</p>
      <div class="orbit__stage" aria-hidden="true">
        <span class="orbit__disc orbit__disc--out"></span>
        <span class="orbit__disc orbit__disc--mid"></span>
        <span class="orbit__disc orbit__disc--in"></span>

        <div class="orbit__ring orbit__ring--in">
          <div class="orbit__core">
            <span class="orbit__here"></span>
            <p class="orbit__k">You are here</p>
            <ul class="orbit__list">
              <li>Client results</li>
              <li>A reputation</li>
              <li>Referrals</li>
              <li>A full calendar</li>
            </ul>
          </div>
        </div>

        <div class="orbit__ring orbit__ring--mid">
          <svg class="orbit__arc" viewBox="0 0 1000 1000"><path id="orbit-arc-mid" d="{arc(292)}"/><text><textPath href="#orbit-arc-mid" startOffset="50%" text-anchor="middle">You need distribution</textPath></text></svg>
          <ul class="orbit__items">
{mid_items}
          </ul>
        </div>

        <div class="orbit__ring orbit__ring--out">
          <svg class="orbit__arc" viewBox="0 0 1000 1000"><path id="orbit-arc-out" d="{arc(452)}"/><text><textPath href="#orbit-arc-out" startOffset="50%" text-anchor="middle">Known beyond your circle</textPath></text></svg>
          <ul class="orbit__items">
{out_items}
          </ul>
        </div>
      </div>

      <figcaption class="orbit__tag">Your expertise already exists.<br><span>We expand who gets to see it.</span></figcaption>
    </figure>'''

out = pathlib.Path(__file__).parent / 'orbit4.html'
out.write_text(html, encoding='utf-8')
print(html[:200])
print('...')
for n, i, a in MID + OUT:
    print(f'{n:28s} {a:6.1f}')
